// <auto-generated>
//   Written by `dotnet run --file scripts/repo-conventions.cs -- grants` from the assembly name
//   of every project in this repository. Do not edit it: regenerate it. `repo-conventions check`
//   fails when it differs from what `grants` would write.
// </auto-generated>
//
// Solution-wide friend grants: Directory.Build.targets links this file into every project, so
// each project's internals are visible to every other. `internal` means solution-internal, and a
// member no other assembly may reach is `private`. A project that sets SolutionFriendGrants to
// false grants nothing, and may declare grants of its own. None of this is a security boundary:
// no family assembly is strong-named. See docs/repository-conventions.md in
// Bennewitz.Ninja.Templates.

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("PkgStem")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("PkgStem.Tests")]
